background_opacity 0.4
background_blur 0
window_border_width 0
window_padding_width 0
draw_minimal_borders yes
# Default colors
#background #232b29
background #192421
foreground #fbdf0a

# Cursor
cursor #F2D5CF
cursor_text_color #dbc93f

# Selection
selection_background #51576D
selection_foreground none

# Normal colors
color0  #51576D
color1  #E78284
color2  #A6D189
color3  #E5C890
color4  #8CAAEE
color5  #F4B8E4
color6  #81C8BE
color7  #B5BFE2

# Bright colors
color8  #626880
color9  #E78284
color10 #A6D189
color11 #E5C890
color12 #8CAAEE
color13 #F4B8E4
color14 #81C8BE
color15 #A5ADCE

# Dim colors
color16 #EF9F76
color17 #F2D5CF

# URL color
url_color #8CAAEE
